apiVersion: appstudio.redhat.com/v1alpha1
kind: EnterpriseContractPolicy
metadata:
  name: redhat-trusted-tasks
  namespace: enterprise-contract-service
spec:
  description: Rules used to verify Tekton Task definitions comply to Red Hat's standards.
  name: Red Hat Trusted Tasks
  sources:
  - config:
      exclude: []
      include:
      - kind
    data:
    - github.com/release-engineering/rhtap-ec-policy//data
    name: Default
    policy:
    - oci::quay.io/conforma/task-policy:konflux@sha256:fb2c1cfc0b68f6aca13eb9c63ae90bbabbc5384818484d8358f66cd9b53d82c9
